spring.application.name=companycrudh2

# Cau hinh H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Su dung H2 Database luu vào file thay vi bo nho RAM
spring.datasource.url=jdbc:h2:file:./data/companydb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# Hibernate cau hinh
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

